name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { xcode_version: '12.4', simulator: 'name=iPhone SE (2nd generation),OS=14.4' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Brew Update
      run:  brew update

    - name: Install Bundler
      run: gem install bundler

    - name: Install Core Utils
      run: if [ -z "$(brew ls --versions coreutils)" ] ; then brew install coreutils ; fi

    - name: Install XCPretty
      run: gem install xcpretty --no-document --quiet

    - name: Show Xcode versions
      run: ls -al /Applications/Xcode*

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.run-config['xcode_version'] }}.app

    - name: Current Xcode Selected
      run: xcode-select -p

    - name: List Simulators
      run:  xcrun simctl list

    - name: Build
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "ExpandableLabelDemoSPM/ExpandableLabelDemoSPM.xcodeproj" -scheme "ExpandableLabelDemoSPM" -destination "${{ matrix.run-config['simulator'] }}" clean build | xcpretty

